### ISSUE TITLE
SJP_INVALID_INPUT on 0

### ISSUE THREAD

**Issue by katef** [sfstewman/sjp#1]
This lexes with an error (below):
```
{
    "hello": 0
}
```
but this lexes fine:
```
{
    "hello": 1
}
```
`0.0` also lexes fine.

I'm printing the token type for each token, where `t=` is `enum SJP_TOKEN` and `r` is the return value from `sjp_lexer_token()`:
```
r=0, t=123 '{'
r=0, t=4 'hello'
r=0, t=58 ':'
sjp error r=-5, t.n=2
```

I didn't see lexer tests for whole json documents to an expected list of tokens output. Can we have those too?

**Comment by sfstewman** [comment]
Thanks for the report!  I had a bug in the condition to check for leading zeros, which I've fixed in 59c4fcd1a929446da10b2625ddd2bdc8c26d51d5.

In terms of lexer tests for whole json documents, I've also added a test with several examples of nested json in c3bfa5464e24d0432577af87e126919a3ed81174

There were previously tests for simpler constructs in the test_simple_array() and test_simple_object() functions:
https://github.com/sfstewman/sjp/blob/c3bfa5464e24d0432577af87e126919a3ed81174/sjp_lexer_test.c#L130-L222

This strikes me as sufficient to show that tokens are being generated correctly, but I'd be happy to add more tests if you have a specific situation you'd like to check.
